AXF/urls.py
from django.contrib import admin
from django.urls import path, include
from App import views
from Api.urls import router as api_router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('App.urls', namespace='App')),
    path('api/', include(api_router.urls)),
    path('', views.home, name='home'),
]

App/urls.py
from django.urls import path, re_path

from . import views

app_name = 'App'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('market/', views.market, name='market'),
    re_path('marketwithparams/(\d+)/(\d+)/(\d+)/$', views.market_with_params, name='market_with_params'),
    path('cart/', views.cart, name='cart'),
    path('mine/', views.mine, name='mine'),
    path('register/', views.register, name='register'),
    path('register_handle/', views.register_handle, name='register_handle'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('login_handle/', views.login_handle, name='login_handle'),
    path('addtocart/', views.add_to_cart, name='add_to_cart'),
    path('addnum/', views.add_num, name='add_num'),
    path('reducenum/', views.reduce_num, name='reduce_num'),
    path('delcart/', views.del_cart, name='del_cart'),
    path('cartselect/', views.cart_select, name='cart_select'),
    path('cartselectall/', views.cart_selectall, name='cart_selectall'),
    path('ordercreate/', views.order_create, name='order_create'),
    re_path('order/(\d+)/$', views.order, name='order'),
    path('order_change_status/', views.order_change_status, name='order_change_status'),
    path('order_wait_pay/', views.order_wait_pay, name='order_wait_pay'),
    path('order_paid/', views.order_paid, name='order_paid'),
    path('order_wait_evaluate/', views.order_wait_evaluate, name='order_wait_evaluate'),
]

templates/base.html
{# 1.加载静态文件 #}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {# bootstrap在google浏览器下需要增加这行 #}
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {# 2. 加载css #}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">

    {# 3. css留空白 #}
    {% block extCSS %}
    {% endblock %}

    <title>{% block title %}django by luomantic{% endblock %}</title>
</head>
<body>
{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

{# 4. 加载js #}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/swiper.jquery.js' %}"></script>
<script src="{% static 'js/base.js' %}"></script>

{# 5. js留空白 #}
{% block extJS %}

{% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    <link rel="stylesheet" href="{% static 'css/base_main.css' %}">
{% endblock %}

{% block header %}
    <header>
        <div style="text-align: center">
            {% block top_content %}
                首页
            {% endblock %}
        </div>
    </header>
{% endblock %}

{% block footer %}
    <footer>
        <a href="{% url 'App:home' %}" class="home">
            <dl>
                <dt><span></span></dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'App:market' %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd>闪购</dd>
            </dl>
        </a>
        <a href="{% url 'App:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'App:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}