AXF/urls.py
from django.contrib import admin
from django.urls import path, include
from App import views
from Api.urls import router as api_router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('App.urls', namespace='App')),
    path('api/', include(api_router.urls)),
    path('', views.home, name='home'),
]

App/urls.py
from django.urls import path, re_path

from . import views

app_name = 'App'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('market/', views.market, name='market'),
    re_path('marketwithparams/(\d+)/(\d+)/(\d+)/$', views.market_with_params, name='market_with_params'),
    path('cart/', views.cart, name='cart'),
    path('mine/', views.mine, name='mine'),
    path('register/', views.register, name='register'),
    path('register_handle/', views.register_handle, name='register_handle'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('login_handle/', views.login_handle, name='login_handle'),
    path('addtocart/', views.add_to_cart, name='add_to_cart'),
    path('addnum/', views.add_num, name='add_num'),
    path('reducenum/', views.reduce_num, name='reduce_num'),
    path('delcart/', views.del_cart, name='del_cart'),
    path('cartselect/', views.cart_select, name='cart_select'),
    path('cartselectall/', views.cart_selectall, name='cart_selectall'),
    path('ordercreate/', views.order_create, name='order_create'),
    re_path('order/(\d+)/$', views.order, name='order'),
    path('order_change_status/', views.order_change_status, name='order_change_status'),
    path('order_wait_pay/', views.order_wait_pay, name='order_wait_pay'),
    path('order_paid/', views.order_paid, name='order_paid'),
    path('order_wait_evaluate/', views.order_wait_evaluate, name='order_wait_evaluate'),
]

templates/user/login.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    <link rel="stylesheet" href="{% static 'app/user/login.css' %}">
{% endblock %}

{% block extJS %}
    <script src="{% static 'app/user/login.js' %}"></script>
{% endblock %}

{% block header %}
    <header>登陆</header>
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'App:login_handle' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label>用户名</label>
                {# id属性是方便js取值， name属性是方便post提交到后台后取值 #}
                <input id="username" name="username" type="text" class="form-control"
                       placeholder="请输入用户名">
            </div>
            <p>{{ msg }}</p>
            <div class="form-group">
                <label>密码</label>
                <input id="password" name="password" type="password" class="form-control" placeholder="请输入密码">
            </div>
            <p>{{ msg }}</p>
            <button id="login" type="submit" class="btn btn-success">登录</button>
        </form>
    </div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    <link rel="stylesheet" href="{% static 'app/user/register.css' %}">
{% endblock %}

{% block extJS %}
    <script src="{% static 'app/user/register.js' %}"></script>
{% endblock %}

{% block header %}
    <header>注册</header>
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'App:register_handle' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label>用户名</label>
                {# id属性是方便js取值， name属性是方便post提交到后台后取值 #}
                <input id="username" name="username" type="text" class="form-control"
                       placeholder="6-18位的数字字母下划线，不能以数字开头">
            </div>
            <p>{{ msg }}</p>

            <div class="form-group">
                <label>密码</label>
                <input id="password" name="password" type="password" class="form-control" placeholder="8位以上字符">
            </div>

            <div class="form-group">
                <label>确认密码</label>
                <input id="again" name="again" type="password" class="form-control" placeholder="请再次输入密码">
            </div>

            <div class="form-group">
                <label>邮箱</label>
                <input id="email" name="email" type="email" class="form-control" placeholder="请输入合法的邮箱">
            </div>

            <div class="form-group">
                <label>头像</label>
                <input id="icon" name="icon" type="file">
            </div>
            <button type="submit" class="btn btn-success">注册</button>
        </form>
    </div>
{% endblock %}